# Generated by Django 2.1.3 on 2018-11-23 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20181122_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='useridas',
            field=models.CharField(default=1984, max_length=500),
            preserve_default=False,
        ),
    ]
