# Generated by Django 2.1.3 on 2018-11-23 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_post_useridas'),
    ]

    operations = [
        migrations.AddField(
            model_name='password',
            name='useridas',
            field=models.CharField(default=1984, max_length=500),
            preserve_default=False,
        ),
    ]
