# Generated by Django 2.1.3 on 2018-11-23 11:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0005_password_useridas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='password',
            name='index',
        ),
        migrations.RemoveField(
            model_name='password',
            name='useridas',
        ),
        migrations.AddField(
            model_name='password',
            name='user',
            field=models.ForeignKey(default=1984, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
