# Generated by Django 2.1.3 on 2018-12-06 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20181123_1319'),
    ]

    operations = [
        migrations.CreateModel(
            name='Generator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upperCase', models.BooleanField(default=False)),
                ('numbers', models.BooleanField(default=False)),
                ('symbols', models.BooleanField(default=False)),
                ('words', models.BooleanField(default=False)),
                ('length', models.CharField(max_length=500)),
            ],
        ),
    ]
