# Generated by Django 2.1.3 on 2018-12-07 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_generator'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Generator',
        ),
    ]
